server:
  port: ${{ secrets.SERVER_PORT }}
spring:
  application:
    name: spring-security-project
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false
  datasource:
    url: jdbc:mysql://${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: ${{ secrets.DB_USERNAME }}
    password: ${{ secrets.DB_PASSWORD }}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        globally_quoted_identifiers: true
        generate_statistics: true
        jdbc:
          batch_size: 100
        cache:
          use_second_level_cache: false
logging:
  level:
    com:
      security: DEBUG
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
