server:
  port: 8081
spring:
  application:
    name: spring-security-project
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false
  datasource:
    url: jdbc:mysql://localhost:3306/db_spring_security
    username: root
    password: 123456
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: none
      naming:
        #        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        physical-strategy: com.security.config.db.CustomNamingStrategy
    properties:
      hibernate:
        globally_quoted_identifiers: true
        generate_statistics: true
        jdbc:
          batch_size: 100
        cache:
          use_second_level_cache: false
        format_sql: true
logging:
  level:
    com:
      security: DEBUG
    org:
      springframework:
        security: DEBUG