server:
  port: 8081
spring:
  application:
    name: spring-security-project
  datasource:
    url: jdbc:mysql://localhost:3306/db_spring_security?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: my-secret-pw
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        generate_statistics: true
        jdbc:
          batch_size: 100
        cache:
          use_second_level_cache: false
        format_sql: true
logging:
  level:
    com:
      security: DEBUG
    org:
      springframework:
        security: DEBUG